#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
# foamCleanTutorials

cp 0/alpha.water.orig 0/alpha.water

rm -rf 0

#------------------------------------------------------------------------------
